name: Help Request
description: Request help regarding the modpack
labels: "auto: help"
body:
- type: checkboxes
  id: exists
  attributes:
    label: Was this help requested before?
    description: You can check using the search bar.
    options:
      - label: "No, it was not."
        required: true

- type: input
  id: log
  attributes:
    label: Please provide a link to your crash report or latest.log, if relevant
    description: "The `latest.log` file is found in `\/logs\/` within the modpack files.\nWe recommend always using https://mclo.gs/." 
    placeholder: https://mclo.gs/MydIQBu...

- type: input
  id: additional-mods
  attributes:
    label: If you have any, please provide a list of additional mods
    description: Leave blank if you have none.
    placeholder: OptiFine, Edible Crayons...

- type: textarea
  id: support-description
  validations:
    required: true
  attributes:
    label: Please describe what you need help with
    description: Try to provide context regarding your setup.
    placeholder: |
      I can't figure this and this out...

- type: markdown
  attributes:
    value: |
      ---
      <a href="https://technicpack.net/modpack/the-1122-pack"><img src="https://i.imgur.com/4ZlB8WC.png" width="64"></a>
