blank_issues_enabled: true
contact_links:
  - name: Community Support Discord
    url: https://bit.ly/the-1122-pack-discord-support
    about: You can get technical support from the community here.
  - name: Community Discussion Discord
    url: https://bit.ly/the-1122-pack-discord-discussion
    about: You can discuss the modpack with the community here.
